[tool.uv]
constraint-dependencies = ['onnxruntime<1.20.0; python_version == "3.9"']

[tool.uv.sources]
livekit-plugins-volcengine = { workspace = true }
livekit-plugins-xunfei = { workspace = true }

[tool.uv.workspace]
members = ["livekit-plugins/*", "livekit-agents"]

[dependency-groups]
dev = [
    "python-dotenv>=1.0.1",
    "mypy",
    "pytest",
    "ruff",
    "pytest-asyncio>=0.25.3",
    "jiwer>=3.1.0",
    "ipykernel>=6.29.5",
    "livekit-plugins-silero>=1.0.17",
    "websockets>=15.0.1",
]

[[tool.uv.index]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
